version: '3.8'

services:
  vpn-parser:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vpn-parser
    restart: unless-stopped
    volumes:
      - ./parser/config:/app/parser/config:ro
      - ./common/database:/app/common/database
      - ./logs:/app/logs
      - ./ovpn_cfgs:/app/src/daemon/ovpn_cfgs
      - ./trash:/app/src/daemon/trash
    environment:
      - TZ=Europe/Moscow
      - LOG_LEVEL=INFO
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # ports:
    #   - "8080:8080"
    # networks:
    #   - my-network

# networks:
#   my-network:
#     driver: bridge